export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE';

export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const FETCH_GENRE_MOVIES = 'FETCH_GENRE_MOVIES';
export const FETCH_GENRE_MOVIES_SUCCESS = 'FETCH_GENRE_MOVIES_SUCCESS';
export const FETCH_GENRE_MOVIES_FAILURE = 'FETCH_GENRE_MOVIES_FAILURE';